### ISSUE TITLE
Should use TryFoo() API?

### ISSUE THREAD

**Issue by knocte** [sdrapkin/SecurityDriven.Inferno#1]
First thing I've read in the documentation is the following bit:

```
Encrypt/Decrypt should do what you expect. Any failure causes NULL to be returned.
```

Shouldn't the failures throw exceptions instead? If the consumer of the API prefers that no exceptions are thrown, then additional bool TryFoo(out bar) methods can be supplied.

**Comment by sdrapkin** [comment]
In case of Encrypt, there should really be no circumstances when null is returned and no exception is thrown. Ie. Encrypt should always succeed & return non-null result or an exception is raised.

In case of Decrypt and Authenticate, "failure" is an expected condition rather than an anomaly. Decrypt will throw on anomalies but will return null on regular decryption-failure events.
