### ISSUE TITLE
Consider serving your website/documentation over HTTPS

### ISSUE THREAD

**Issue by JoshuaWebb** [sdrapkin/SecurityDriven.Inferno#23]
There's something a little ironic about the documentation of a crypto library being hosted with HTTP in 2019, especially with the way Google/Chrome treats pages served over HTTP these days.

While it has no bearing on the security/implementation of the library, it doesn't project the best image.

![image](https://user-images.githubusercontent.com/6722399/52321701-20df2a00-2a2a-11e9-844e-cc9aa4389f75.png)

**Comment by sdrapkin** [comment]
If someone donates enough to cover CloudFront costs, I'll put a CloudFront with ACM cert in front of S3 bucket.

**Comment by cocowalla** [comment]
Cloudflare's free tier is really generous - is that something you could use?

**Comment by sdrapkin** [comment]
@cocowalla Cloudflare is not without issues. I would have to give up DNS control (not very appealing), and every now and then Cloudflare decides that I'm not human-enough and does not show me Cloudflare-fronted sites (temporarily). I don't like being at the mercy of their magic algorithms.

**Comment by cocowalla** [comment]
I've only ever seen Cloudflare asking for captchas for Tor connections, but I guess there are other situations where it happens. 

Not sure I understand what you mean about giving up DNS control, unless you really are hosting your own name server(s)?

I find Cloudflare to be good enough for most cases, especially since you are getting essentially zero-config TLS in front of your site for free (and caching too, if you want it), but obviously it's your domain 😃

**Comment by sdrapkin** [comment]
How's that: [https://securitydriven.net/inferno](https://securitydriven.net/inferno) ?

**Comment by JoshuaWebb** [comment]
Looks good to me 👍
