### ISSUE TITLE
Can this library be used as foundation for a bitcoin library?

### ISSUE THREAD

**Issue by MithrilMan** [sdrapkin/SecurityDriven.Inferno#24]
bitcoin uses RIPEMD160, SHA256, ECDSA on Secp256k1 curve.

Does this library support these algorithms?

**Comment by sdrapkin** [comment]
@MithrilMan RIPEMD160 and SHA256 are available in .NET (there is nothing special in **Inferno** to support these hashing schemes). Base58 encoder/decoder is not in **Inferno**. Lastly, **Inferno** uses NIST P-384 elliptic curve, while bitcoin uses Secp256k1 elliptic curve.

**Comment by MithrilMan** [comment]
Thanks for the clarification.

Actually in our project we are using BouncyCastle implementation of the stuffs we need.
During IBD (Initial Block Download) of our fullnode we see a lot of memory fragmentation in the heap and TaskManager reports that our service is taking almost the double of what it really uses (this is because a lot of memory is free but not collected).
I suspect this is because we may have a lot of allocation that we can save and serialization and crypto classes may be the reason. From your experience does implementing Span/ReadonlySpan helps on this regard?

**Comment by sdrapkin** [comment]
@MithrilMan From my experience, BouncyCastle is just fundamentally poorly-coded for .NET. It's not even about seeking Span/ReadOnlySpan efficiencies - it's about having .NET experts who also happen to be expert cryptographers. This dual-skill is almost impossible to find. DJB might be one example in C-expertise and crypto-experise. BouncyCastle authors are very skilled in crypto, but not in .NET.

Inferno offers very high efficiency (cpu & GC) even without Span/ReadOnlySpan. I'm able to get away with not having DJB-level of crypto expertise by relying on FIPS-certifed crypto implementations already shipping with .NET or Windows-OS, using the simplest safe modes (ex. CTR and encrypt-them-mac instead of GCM), and being extremely-careful leveraging 18+ years of .NET expertise without messing up crypto.

The memory fragmentation you're experiencing is unlikely to be cured by Span techniques, because such fragmentation is likely caused by allocations which are long-lived (ie. survive gen-0 and gen-1 collections). A better idea is to review all allocations and ensure that they are all either collected in gen-0, or survive gen-2 (ie. live-forever, in which case you should try to front-load all such allocations to minimize fragmentation). I'll skip the LOH lecture - I'm sure you're aware.

**Comment by MithrilMan** [comment]
I guess when you say "in which case you should try to front-load all such allocations to minimize fragmentation" you mean using technique like object pooling right?
Even if our objects are quite dynamic, their size can vary (they are composed objects that take quite a lot of size and are built from a serialized streem that comes from other peers and the size vary a lot)
P.S.
I confirm that fragmentation is on both gen2 and LOH level (more on gen2)

**Comment by sdrapkin** [comment]
Yes, I meant pooling, but ideally not object-pooling (your objects are dynamically-sized), but byte-array pooling - ie. keeping our objects in raw byte-array form, which is easy to pool, and using ex. a flyweight pattern to map Spans of typed structures over your byte-arrays just-in-time, to minimize GC-traffic.
