### ISSUE TITLE
FromB64 vs FromB64Url

### ISSUE THREAD

**Issue by ItSkary** [sdrapkin/SecurityDriven.Inferno#43]
I am quite confused, if i try to decode a base64 with FromB64 extension method, it will return NULL.

`"MTM2LDI3Mg==".FromB64() --> NULL`
`"MTM2LDI3Mg==".FromB64Url() --> byte[] {49,51,54,44,50,55,50} //correct`
`"MTM2LDI3Mg==".FromB64Url().FromBytes()` -->throw System.ArgumentException 'bytes' array must have even number of bytes\r\nParameter name: bytes

It's not clear to me the difference between the two methods FromB64() and FromB64Url(). Seems like the first one handle only base64 generated by this library, that is somewhat slightly different from the one i have (generated by a third party).
The base64 i get, contain few number (in a csv format), represented by ascii character, in my example it contain : "136,272"

**Comment by sdrapkin** [comment]
- `ToBase64Url()`/`FromBase64Url()` provide base64 web-safe encoding (padless) from [RFC 4648](https://tools.ietf.org/html/rfc4648#section-5).
- `ToB64()`/`FromB64()` provide equivalent of [.NET Framework 4.x](https://learn.microsoft.com/en-us/dotnet/api/system.web.httpserverutility.urltokenencode?view=netframework-4.8#system-web-httpserverutility-urltokenencode(system-byte())) `UrlTokenEncode()`/`UrlTokenDecode()`, which Microsoft implemented as non-standard (yet URL-safe) encoding that adds either `0`, `1`, or `2` to the end instead of multiple `=`.
- `ToBytes()`/`FromBytes()` provide an unambiguous secure conversion of any valid .NET `string` to `byte[]` and back. It uses 2 bytes for each 1 character.

**Comment by ItSkary** [comment]
So basically i need the first one (FromBase64Url), because i need to convert back a standard Base64.

But is not clear to me why i am missing, because seem i can't chain FromBase64Url and FromBytes to safely decode a third party Base64 (sorry for this little OT). Is the fact that, as you stated, it's paddless that does not allow me to make a conversion?

**Comment by sdrapkin** [comment]
You can only use `FromBytes()` on byte-arrays that were encoded with `ToBytes()`. If you have 3rd-party data that is Base64-encoded, they likely used either padded or padless standard Base64 encoding (ie. you'd use either built-in `Convert.FromBase64String()` or Inferno's `FromBase64Url()` to get the original byte-array).

The other aspect is what that original byte-array actually represents, and how to convert it into something else - that's specific to your particular scenario.

**Comment by ItSkary** [comment]
Ah ok, thanks for clarification, i will rely on `Encoding.UTF8.GetString` then, so i go back from a byte array to string
